version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: servico_pedidos
      PGDATA: /data/postgres
    networks:
        - my_network
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # Porta para acessar a interface de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - my_network

  app:
    build: .
    container_name: servico_pedidos_app
    networks:
      - my_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/servico_pedidos
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_RABBITMQ_HOST: rabbitmq
    ports:
      - "8080:9000"
    depends_on:
      - postgres
      - rabbitmq

networks:
  my_network:
    driver: bridge

volumes:
  pgdata:

